#!/bin/bash

arg="$*"

function processDir()
{
    local nowDir=$PWD
    # now timestamp
    #local timestamp=`eval date +%s`
    # timestamp for dir modify
    local timestamp=`eval stat -c%Y $*`
    fname="$*_$timestamp"
    echo $fname
    #echo $*
    cd "$*"
    for f in *
    do
        if [[ -d $f ]]
        then
            #echo $f is dir
            processDir "$f"
        fi
    done
    cd $nowDir
}

# Check the argument
if [[ ! -e $arg ]]
then echo "Dir not found!"
    exit 1
fi

if [[ ! -d $arg ]]
then echo "Argument is not a dir!"
    exit 1
fi

if [[ ! -r $arg ]]
then echo "Dir can't be readed!"
    exit 1
fi

if [[ ! -w $arg ]]
then echo "Dir can't be writed!"
    exit 1
fi
# --------

base=`basename $arg`

cd "$arg"
cd ..
processDir "$base"

exit 0

